### ISSUE TITLE
Get writing portfolio to presentable state

### ISSUE THREAD

**Issue by emmadempseyprofessional** [emmadempseyprofessional/professionalwebsite#14]
- [x] Create the three buttons for the three sample texts
- [x] Ensure all the text displays properly within the $secondary border
- [x] Back to top button
- [x] Review button positioning for different screen sizes
- [x] Fix fonts / colors for title and directions

**Comment by seanmcnamee** [comment]
Ready for your review @emmadempseyprofessional

**Comment by seanmcnamee** [comment]
To review button positioning for different screen sizes
