### ISSUE TITLE
Resume download functionality

### ISSUE THREAD

**Issue by emmadempseyprofessional** [emmadempseyprofessional/professionalwebsite#17]
When user clicks resume on the navbar, drop down will appear. One option is for preview that will open the resume in the browser. The other option says download and would immediately send the .pdf file of the resume to the user's downloads.

**Comment by emmadempseyprofessional** [comment]
Saving this for the end, since I'm waiting to update the resume with the website domain. Once that happens I'll update it with the new domain as a .pdf, and we can add this functionality. In the mean time, I will add the drop down bar.

**Comment by emmadempseyprofessional** [comment]
Actually, i dont know how to make a drop down.  help!

**Comment by seanmcnamee** [comment]
Ready for your review @emmadempseyprofessional
