### ISSUE TITLE
Aesthetic changes to the navbar

### ISSUE THREAD

**Issue by emmadempseyprofessional** [emmadempseyprofessional/professionalwebsite#18]
- [x] Use correct font for the navbar items (portfolio resume contact)
- [x] Improve spacing of the navbar items to more accurately look like wireframe
- [x] Update collapse button to display as leftarrow.png and rightarrow.png 
- [x] Ensure the navbar items are 1/3 (instead of 1/2) from the top

**Comment by seanmcnamee** [comment]
@emmadempseyprofessional let me know if the current spacing for the navbar items is OK.

Additionally, I've made your icon in the navbar the icon that shows on the browser tab. If this shouldn't have the white border or should be something else, please upload

**Comment by seanmcnamee** [comment]
I also think there should be a visual indicator for the current page a user is on - can we change the background of the navbar items?

Answer: No

**Comment by emmadempseyprofessional** [comment]
New browser icon was uploaded to public (rawlogo.png). You can use that one instead.
