### ISSUE TITLE
Nav bar updates

### ISSUE THREAD

**Issue by emmadempseyprofessional** [emmadempseyprofessional/professionalwebsite#4]
- Update font to MADE Tommy
- Resize so that each menu item is spaced better on the page
- Update the collapse arrow to the one from the wireframe to match aesthetic
- Ensure that resume has a dropdown menu as well, 2 options: preview and download

**Comment by seanmcnamee** [comment]
related to fonts https://stackoverflow.com/a/49879344 #9

**Comment by seanmcnamee** [comment]
@emmadempseyprofessional make sure the arrow picture is uploaded
